Feature: User confirmation by email
BrightCoders-Institute/proyecto-final-bcmay23-ror-team1 pull request #104
Opened 2023-09-14 22:31 UTC by JuanMichel16

# Description
The user confirmation by email added

## What
The application will send email to user for confirmation his account.

See https://github.com/BrightCoders-Institute/proyecto-final-bcmay23-ror-team1/issues/93 for more information.

## Why
This feature will allow to validate the new users.

See https://github.com/BrightCoders-Institute/proyecto-final-bcmay23-ror-team1/issues/93 for more information.

## Screenshots
-  message about the email
![image](https://github.com/BrightCoders-Institute/proyecto-final-bcmay23-ror-team1/assets/54423117/77148aac-b0fb-4282-989b-48ee8816e613)

- Email with the link for confirmation
![image](https://github.com/BrightCoders-Institute/proyecto-final-bcmay23-ror-team1/assets/54423117/43c16736-e7a6-43a2-b159-639d5f679b26)

2023-09-18 17:02 UTC, claunicole requested changes

2023-09-18 17:02 UTC, claunicole commented on config/environments/development.rb
> +  config.action_mailer.delivery_method = :smtp
for username and password it is better to have the credentials in a .ENV file

2023-09-19 20:30 UTC, JoseGabino12 approved these changes
🚀

2023-09-19 20:31 UTC, sjlwa approved these changes
🖌️

2023-09-19 20:31 UTC, Branyoe approved these changes

2023-09-19 20:31 UTC, merged