Feat/delete post
BrightCoders-Institute/proyecto-final-bcmay23-ror-team1 pull request #36
Opened 2023-08-10 22:19 UTC by JuanMichel16

# Description
Method to delete post has been added and I added some code refactoring.

## What
- Method destroy in post controller added.
- Index method modified in post controller to get better performance.

See https://github.com/orgs/BrightCoders-Institute/projects/83?pane=issue&itemId=35008512 for more information.

## Why
- The users will be able to delete their posts.
- In the index method, the code made several requests in the database when it received the information.

See https://github.com/orgs/BrightCoders-Institute/projects/83?pane=issue&itemId=35008512 for more information.

Examples:

## Testing
- I created some post as test and later I deleted it.

## Screenshots

### Code refactoring and destroy method created
![image](https://github.com/BrightCoders-Institute/proyecto-final-bcmay23-ror-team1/assets/54423117/e2655989-589c-4efb-97f6-3f00e932b87a)

![image](https://github.com/BrightCoders-Institute/proyecto-final-bcmay23-ror-team1/assets/54423117/f00937ab-2c73-4a78-a09d-48aa5701673f)

### When I created some several posts
![image](https://github.com/BrightCoders-Institute/proyecto-final-bcmay23-ror-team1/assets/54423117/6c28efb0-1af5-4d2b-972d-50ea7966520c)

### After I deleted two posts
![image](https://github.com/BrightCoders-Institute/proyecto-final-bcmay23-ror-team1/assets/54423117/a71e94ab-9e0c-413f-ac4e-8b23c79e8ac9)

2023-08-11 00:11 UTC, claunicole requested changes

2023-08-11 00:11 UTC, claunicole commented on app/assets/stylesheets/sass/home.scss
> +  background-color: $colorBlack;
sort alphabetically

2023-08-11 00:11 UTC, claunicole commented on app/assets/stylesheets/sass/home.scss
> +  width: 75%;
sort this too

2023-08-11 00:11 UTC, claunicole commented on app/assets/stylesheets/sass/posts.scss
> +      color: #999;
sort alphabetically

2023-08-11 00:11 UTC, claunicole commented on app/assets/stylesheets/sass/posts.scss
> +    display: flex;
this too

2023-08-12 00:02 UTC, sjlwa approved these changes
Resolve conflicts

2023-08-12 00:02 UTC, Branyoe approved these changes

2023-08-12 00:28 UTC, merged