Feat/profile view
BrightCoders-Institute/proyecto-final-bcmay23-ror-team1 pull request #75
Opened 2023-09-06 00:43 UTC by Branyoe

## What
- Added the view that shows the profile information.
- added modal that edits profile information.

## Screenshots
![image](https://github.com/BrightCoders-Institute/proyecto-final-bcmay23-ror-team1/assets/65278575/5fc646b1-692b-4177-b824-62a14b165036)
![image](https://github.com/BrightCoders-Institute/proyecto-final-bcmay23-ror-team1/assets/65278575/2919a546-b0b6-4a18-99d5-edeb9e18de91)

2023-09-06 01:29 UTC, sjlwa requested changes
💯

2023-09-06 01:29 UTC, sjlwa commented on app/assets/stylesheets/app.scss
> +  "./sass/profile_view";
replace ; to ,

2023-09-06 01:29 UTC, sjlwa commented on app/assets/stylesheets/sass/abstracts/colors.scss
> +$colorEmptyBg: #333639
; missing

2023-09-06 01:29 UTC, sjlwa commented on app/assets/stylesheets/sass/edit_view.scss
sort every attribute alphabetically

2023-09-06 01:29 UTC, sjlwa commented on app/assets/stylesheets/sass/profile_view.scss
sort every attribute alphabetically

2023-09-06 01:29 UTC, sjlwa commented on app/assets/stylesheets/app.scss
> -
unused

2023-09-06 01:29 UTC, sjlwa commented on app/assets/stylesheets/sass/profile_view.scss
> +  // display: none;
unused

2023-09-07 01:47 UTC, sjlwa approved these changes
👍🏽

2023-09-07 01:58 UTC, JoseGabino12 approved these changes
LGTM

2023-09-07 02:01 UTC, merged